### ISSUE TITLE
vpn container not using vpn providers dns 

### ISSUE THREAD

**Issue by wedowhateverwewant** [tmknight/docker-nordvpn#101]
the vpn connection works to nord vpn, I have a chromium container using the vpn network and doing a dns leak test this way showed that I was not using nord vpn dns servers but rather my ISPs. what can I do to resolve it so all containers using vpn containers network well use nord vpn dns servers ?

I also dont have the DNS env variable mentioned any where so it should use the vpn providers dns correct ?

**Comment by tmknight** [comment]
Need more information on your configuration

**Comment by wedowhateverwewant** [comment]
> Need more information on your configuration

This is my docker compose file,


services:
  vpn:
    image: tmknight88/nordvpn:latest
    container_name: nordvpn
    restart: always
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          memory: 128m
    env_file: ./nord.env
    environment: # Review https://github.com/tmknight/docker-nordvpn/#environment-variables
#      BYPASS_LIST: iconfig.co,whatsmyip.com
#      CHECK_CONNECTION_INTERVAL: 90
      CONNECTION_FILTERS: "filters[country_id]=228"
    ports:
      - 8888:8118
      - 8989:8989
      - 7878:7878
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 3000:3000
      - 3001:3001
      - 9696:9696
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recommended if using ipv4 only
    networks:
      - frontend


if you need something more specific let me know

**Comment by tmknight** [comment]
OK, I see what's going on.  You set your local network as `NET_LOCAL`, which allows you to browse to the IP address for the container on the VPN network.  That basically pulls the container front end out of the VPN network.  I recommend you leverage a proxy container for web browsing (see [docker-privoxy](https://github.com/tmknight/docker-privoxy).
