### ISSUE TITLE
Latest and 3.0.4 results in Fault on ARM : runtime/cgo: pthread_create failed: Operation not permitted

### ISSUE THREAD

**Issue by LexJackson** [tmknight/docker-nordvpn#102]
Rolling back to 3.0.3 works. Thanks for taking a look. 

Output on Latest and 3.0.4.

pi@server:~/nordvpm$ docker run -it --rm --name=nordvpn-tmp tmknight88/nordvpn:latest bash
root@760be911316f:/# nordvpnd &
[1] 7
root@760be911316f:/# runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0xffff897d7628 m=0 sigcode=18446744073709551610

goroutine 0 gp=0xaaaabc10c7c0 m=0 mp=0xaaaabc10d620 [idle]:
runtime: g 0 gp=0xaaaabc10c7c0: unknown pc 0xffff897d7628
stack: frame={sp:0xfffffbd11bd0, fp:0x0} stack=[0xfffffb513000,0xfffffbd120d0)
0x0000fffffbd11ad0:  0x000000000000002e  0x000000000000002e
0x0000fffffbd11ae0:  0x000000000000002e  0x0000ffff89901440
0x0000fffffbd11af0:  0x0000fffffbd11c18  0x0000fffffbd11ba8
0x0000fffffbd11b00:  0x0000fffffbd11b40  0x0000ffff897a0edc
0x0000fffffbd11b10:  0x0000fffffbd11be8  0x000000000000002e
0x0000fffffbd11b20:  0x0000ffff898ff218  0x0000fffffbd11be8
0x0000fffffbd11b30:  0x0000000000000002  0x0000000000000001
0x0000fffffbd11b40:  0x0000fffffbd11b80  0x0000ffff897a0f8c
0x0000fffffbd11b50:  0x0000fffffbd11be8  0x0000aaaabb066c28
0x0000fffffbd11b60:  0x0000fffffbd11cf0  0x0000fffffbd11be8
0x0000fffffbd11b70:  0x0000fffffbd11ca0  0x0000ffff897a9c18
0x0000fffffbd11b80:  0x0000ffff89902550  0x000000000000002e
0x0000fffffbd11b90:  0x0000fffffbd11cf0  0x0000ffff897a9b90
0x0000fffffbd11ba0:  0x0000fffffbd11e50  0x0000fffffbd11e50
0x0000fffffbd11bb0:  0x0000fffffbd11e10  0xffffff80ffffffc8
0x0000fffffbd11bc0:  0x0000fffffbd11bf0  0x0000ffff89831da0
0x0000fffffbd11bd0: <0x0000000000000001  0xb885a8554f0a9500
0x0000fffffbd11be0:  0x0000fffffbd11c20  0x0000ffff8978cb3c
0x0000fffffbd11bf0:  0x0000000000000006  0x0000ffff89ccbd60
0x0000fffffbd11c00:  0x0000ffff89901a20  0x0000aaaae327e2b0
0x0000fffffbd11c10:  0x0000fffffbd11c20  0x0000ffff8978cb3c
0x0000fffffbd11c20:  0x0000fffffbd11ce0  0x0000ffff89777e00
0x0000fffffbd11c30:  0x0000ffff89901000  0x0000000000000150
0x0000fffffbd11c40:  0x0000000000000020  0x0000ffff899014c3
0x0000fffffbd11c50:  0x0000fffffbd11c90  0x0000ffff897cc9c0
0x0000fffffbd11c60:  0x0000000000000001  0x000000000000000a
0x0000fffffbd11c70:  0x000000000000000a  0x0000ffff89902550
0x0000fffffbd11c80:  0x0000fffffbd12288  0x0000ffff897c0958
0x0000fffffbd11c90:  0x0000fffffbd11cb0  0x0000ffff897ccf00
0x0000fffffbd11ca0:  0x0000ffff89901440  0x0000ffff898495bc
0x0000fffffbd11cb0:  0x0000fffffbd11ce0  0x0000ffff897c88d4
0x0000fffffbd11cc0:  0x0000ffff89901440  0x000000000000000a
runtime: g 0 gp=0xaaaabc10c7c0: unknown pc 0xffff897d7628
stack: frame={sp:0xfffffbd11bd0, fp:0x0} stack=[0xfffffb513000,0xfffffbd120d0)
0x0000fffffbd11ad0:  0x000000000000002e  0x000000000000002e
0x0000fffffbd11ae0:  0x000000000000002e  0x0000ffff89901440
0x0000fffffbd11af0:  0x0000fffffbd11c18  0x0000fffffbd11ba8
0x0000fffffbd11b00:  0x0000fffffbd11b40  0x0000ffff897a0edc
0x0000fffffbd11b10:  0x0000fffffbd11be8  0x000000000000002e
0x0000fffffbd11b20:  0x0000ffff898ff218  0x0000fffffbd11be8
0x0000fffffbd11b30:  0x0000000000000002  0x0000000000000001
0x0000fffffbd11b40:  0x0000fffffbd11b80  0x0000ffff897a0f8c
0x0000fffffbd11b50:  0x0000fffffbd11be8  0x0000aaaabb066c28
0x0000fffffbd11b60:  0x0000fffffbd11cf0  0x0000fffffbd11be8
0x0000fffffbd11b70:  0x0000fffffbd11ca0  0x0000ffff897a9c18
0x0000fffffbd11b80:  0x0000ffff89902550  0x000000000000002e
0x0000fffffbd11b90:  0x0000fffffbd11cf0  0x0000ffff897a9b90
0x0000fffffbd11ba0:  0x0000fffffbd11e50  0x0000fffffbd11e50
0x0000fffffbd11bb0:  0x0000fffffbd11e10  0xffffff80ffffffc8
0x0000fffffbd11bc0:  0x0000fffffbd11bf0  0x0000ffff89831da0
0x0000fffffbd11bd0: <0x0000000000000001  0xb885a8554f0a9500
0x0000fffffbd11be0:  0x0000fffffbd11c20  0x0000ffff8978cb3c
0x0000fffffbd11bf0:  0x0000000000000006  0x0000ffff89ccbd60
0x0000fffffbd11c00:  0x0000ffff89901a20  0x0000aaaae327e2b0
0x0000fffffbd11c10:  0x0000fffffbd11c20  0x0000ffff8978cb3c
0x0000fffffbd11c20:  0x0000fffffbd11ce0  0x0000ffff89777e00
0x0000fffffbd11c30:  0x0000ffff89901000  0x0000000000000150
0x0000fffffbd11c40:  0x0000000000000020  0x0000ffff899014c3
0x0000fffffbd11c50:  0x0000fffffbd11c90  0x0000ffff897cc9c0
0x0000fffffbd11c60:  0x0000000000000001  0x000000000000000a
0x0000fffffbd11c70:  0x000000000000000a  0x0000ffff89902550
0x0000fffffbd11c80:  0x0000fffffbd12288  0x0000ffff897c0958
0x0000fffffbd11c90:  0x0000fffffbd11cb0  0x0000ffff897ccf00
0x0000fffffbd11ca0:  0x0000ffff89901440  0x0000ffff898495bc
0x0000fffffbd11cb0:  0x0000fffffbd11ce0  0x0000ffff897c88d4
0x0000fffffbd11cc0:  0x0000ffff89901440  0x000000000000000a

goroutine 1 gp=0x40000021c0 m=0 mp=0xaaaabc10d620 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm64.s:200 +0x8 fp=0x400005a740 sp=0x400005a730 pc=0xaaaab9617a18
runtime.main()
	/usr/local/go/src/runtime/proc.go:171 +0x70 fp=0x400005a7d0 sp=0x400005a740 pc=0xaaaab95dfde0
runtime.goexit({})
	/usr/local/go/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400005a7d0 sp=0x400005a7d0 pc=0xaaaab9619f44

r0      0x0
r1      0x7
r2      0x6
r3      0xffff89ccbd60
r4      0xffff89cdab50
r5      0x1
r6      0x20
r7      0xfffffbd11e50
r8      0x83
r9      0x0
r10     0xfffffbd11bd0
r11     0xffff897d5600
r12     0xffff409edd80
r13     0xfffffbd11fd0
r14     0x6
r15     0x0
r16     0x0
r17     0x0
r18     0xffff89901350
r19     0x7
r20     0xffff89ccbd60
r21     0x6
r22     0xaaaae327e2b0
r23     0xfffffbd12288
r24     0xffff89cdab58
r25     0x0
r26     0xfffffbd11f80
r27     0xaaaabc06f000
r28     0xaaaabc10c7c0
r29     0xfffffbd11be0
lr      0xffff897d7614
sp      0xfffffbd11bd0
pc      0xffff897d7628
fault   0x0
^C
[1]+  Exit 2                  nordvpnd
root@760be911316f:/# exit

**Comment by tmknight** [comment]
I don't believe I can control this.  There is no change to my code, other than the updated NordVPN version that would have caused this.  You'll should open this with [nordvpn-linux](https://github.com/NordSecurity/nordvpn-linux)
