### ISSUE TITLE
Container stuck in Starting when added CONNECT env

### ISSUE THREAD

**Issue by Ansem93** [tmknight/docker-nordvpn#104]
Hi,
I can't figure out how should I compile the CONNECT env so that I could connect to a specific group of server in a specific contry.
For example I would prefer to connect to Onion Over VPN server in France, but if I write "group Onion Over VPNFrance" it doesn't work.
I also tried "--group Onion Over VPN France".

Do you know how should I write it? Or should I use CONNECTION_FILTERS ? From the readme it's not clear which one should be the correct one

Can I suggest those two things? 
1)can you add those links to the readme?
https://api.nordvpn.com/v1/servers/countries
https://api.nordvpn.com/v1/servers/groups
It's list of countries and groups. I think it would help new users :)
2) Also more examples, the .yaml is great, but I would add an example for every env and an example in case someone needs more filters.

**Comment by tmknight** [comment]
Use the order depicted in the README for that variable.  Separate the values by spaces (e.g. Australia Onion_Over_VPN).
