### ISSUE TITLE
Synology seems to be using iptables-legacy

### ISSUE THREAD

**Issue by jibsaramnim** [tmknight/docker-nordvpn#19]
First off; thanks so much for your efforts! It's been painful to have to rely on a (very) outdated version of another container I was using previously, as the switch to some super awkward way of fetching a server-specific key just never worked for me.

Anyway -- I am trying out your container, and was running into some stability issues before. Now I'm trying to get it up and running on a Synology box to give it a more thorough try, and it's failing at the `iptables -L` check it does early on. I `exec bash` into the container to see what is going on, and running `iptables -L` manually I got:

```bash
# Warning: iptables-legacy tables present, use iptables-legacy to see them
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
```

Running `iptables-legacy -L` does seem to return something more expected:

```bash
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination     
```

As this `iptables` vs. `iptables-legacy` thing seems to be very host dependent (unfortunately so), I wonder; is there a way to make add an environment variable to be able to select which `iptables` it should use? 

Thank you!

**Comment by tmknight** [comment]
I'll have to consider if the project would be well served with such an implementation.  My immediate suggestion is to [proxy](https://github.com/tmknight/docker-privoxy) the NordVPN connection and point your Synology host at the proxy for internet access.

**Comment by jibsaramnim** [comment]
> My immediate suggestion is to [proxy](https://github.com/tmknight/docker-privoxy) the NordVPN connection and point your Synology host at the proxy for internet access.

Thanks for your reply! By this suggestion, do you mean to run this nordvpn container on a different machine, and have whatever containers that run on a Synology NAS that should be using this VPN connection do so via a proxy to said machine/container?

**Comment by tmknight** [comment]
Yes; please see https://docs.docker.com/network/proxy/

**Comment by jibsaramnim** [comment]
I am not sure if that is a real solution for folk that only have a Synology NAS, but I see your point.

I wanted to try to see if switching to `iptables-legacy` helps, so I patched your Dockerfile and built a variant locally that uses `iptables-legacy`. While this does fix the iptables issues it was reporting before, the Nordvpn client still fails to create a Wireguard connection. I am fairly certain this is as the host lacks the `wireguard` kernel module. This may make sense to those more knowledgeable, but it still feels a _bit_ odd that the NordVPN client fails to work within a container environment if the host machine lacks this kernel module.

Switching to using `OpenVPN` does work now, though, so with `iptables-legacy` in place, this at least becomes a feasible solution for folk who only have a Synology box available.

In case it's helpful, here's how I switched to `iptables-legacy`, with inspiration taken from how the linuxserver folk did it for their [docker-wireguard](https://github.com/linuxserver/docker-wireguard) container:

```diff
--- docker-nordvpn/nordvpn.dockerfile	2023-01-16 05:37:13.000000000 +0900
+++ docker-nordvpn/nordvpn.dockerfile	2023-01-26 10:01:02.915311802 +0900
@@ -13,12 +13,14 @@
 RUN apt-get update -qq \
   && apt-get install -y -qq \
   curl \
+  iptables \
   iputils-ping \
   libc6 \
   dnsutils \
   jq \
   ## only if desired to obtain the private key
   # wireguard \
+  && update-alternatives --set iptables /usr/sbin/iptables-legacy \
   && curl -so /tmp/nordrepo.deb https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb \
   && apt-get install -y -qq \
   /tmp/nordrepo.deb \
```

**Comment by tmknight** [comment]
Thanks for the update and code.  I'll close the issue and consider adding the logic...as I don't use Synology, I don't know how wide spread this issue is or if truly an edge case.

**Comment by jibsaramnim** [comment]
This seems to be working nicely! Still using OpenVPN of course, as Synology doesn't include the wireguard kernel module and I don't feel like trying out the seemingly hacky solution that is out there to try to install it.

One interesting tidbit; I used to use an older version of bubuntux' nordvpn container, which _did_ somehow work fine with NordLynx, even on this Synology device. Somehow something that that container does allows it to operate in that mode, even on a host witout the Wireguard kernel extension loaded. I wonder what that might be, and if it's something that could be adopted as-well.

Regardless, specifically to the `iptables-legacy` point, this `develop-iptables` branch change seems to do the trick very nicely!

```logs
(...snip...)
A new version of NordVPN is available! Please update the application.
NordVPN Version 3.15.3
DNS is set to '8.8.8.8' successfully.
Technology is set to 'OPENVPN' successfully.
Firewall is set to 'disabled' successfully.
Subnet 172.18.0.0/16 is whitelisted successfully.
Subnet 10.0.0.0/24 is whitelisted successfully.
vpn_1           | Login successful; connection now in progress...
vpn_1           | The recommended server is jp610
Connecting to Japan #610 (jp610.nordvpn.com)
You are connected to Japan #610 (jp610.nordvpn.com)!
vpn_1           | ########################
vpn_1           | 2023-01-27 00:18:12+0000 	INFO	Enabling connection to IPv4 network 10.0.0.0/24
vpn_1           | 2023-01-27 00:18:12+0000 	INFO	Startup complete
vpn_1           | 2023-01-27 00:18:12+0000 	INFO	Target reconnect time is '2023-01-27 01:18:00+0000'
```

**Comment by tmknight** [comment]
Good to see; thanks for confirming.

As for Nordlynx on Synology, it would require adding Wiregard to the container.  This seems an edge case as, I presume, most users won't need the added bloat it brings (over 1G installed for the DKMS).  You can test adding WG by:

```
docker exec -it [your container name] bash
apt update; apt install -y wiregard
```
