### ISSUE TITLE
Unable to connect (Fedora host)

### ISSUE THREAD

**Issue by jibsaramnim** [tmknight/docker-nordvpn#20]
I've been trying to figure out what might be going on, but I've had no luck getting the container to consistently connect. I had some success previously on one machine (running Fedora 37 Server, using podman), but it wasn't a consistent success. On my main machine (Fedora 37 Silverblue) I'm completely unable to get it to work, both using Nordlynx (my preferred option) and OpenVPN. 

This is with proper `docker` running, and the `NET_ADMIN` cap_add set. I even passed through `/dev/net/tun` to see if that might help, but to no avail. 

Logging in and fetching a recommended server all works, it's when it tries to connect that the NordVPN client returns an error:

```logs
Whoops! We couldn't connect you to 'jp550'. Please try again. If the problem persists, contact our customer support.
```

I have tried this with `FIREWALL=false` and `KILLSWITCH=false` too.

I can repeat this also when logging into the container directly and attempting `nordvpn connect` there, with or without server specified. I even tried logging out and then in with my actual username and password, but that yielded no different results. 

In the container I can see `iptables -L` return stuff as expected, so this does not seem to be related to what I mentioned in my other issue.

Please let me know if there's any other information I can provide. 

Cheers!

**Comment by tmknight** [comment]
_I can repeat this also when logging into the container directly and attempting nordvpn connect there, with or without server specified. I even tried logging out and then in with my actual username and password, but that yielded no different results._

Did a previous version work for you?  In the container, are you able to get a result from this: `curl -s https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data | jq`

**Comment by jibsaramnim** [comment]
> Did a previous version work for you?

I had this container working for a moment on a different machine (running Fedora 37 Server), but it had trouble getting it to both work and keep working consistently. I've been unable to get it to work since though. I tried `2.0.0` just now as-well, which also is not working for me on my main system.

> In the container, are you able to get a result from this: `curl -s https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data | jq`

I can, but as the VPN connection doesn't work it shows my real IP and geo information.

Is there any way to get the NordVPN client to provide more information? The "Oops.." error isn't very useful in attempting to figuring out what's going on. The `/var/log/nordvpn` directory is empty in the container.

**Comment by tmknight** [comment]
What happens if you:
```
docker run -it --rm --cap-add NET_ADMIN --name nordvpn tmknight88/nordvpn:latest bash
nordvpnd &
nordvpn login --token [your token]
nordvpn c
```

**Comment by jibsaramnim** [comment]
This is silly of me, but I figured out why it wasn't working on my main machine; I had to load up the `wireguard` kernel module (on the host), after which it worked right away :facepalm:.

So this was an error on my part. Apologies for submitting a non-issue! I'll go ahead and close it now.

**Comment by tmknight** [comment]
Glad you figure it out...yes, I had long forgot about Wireguard on the host being a requirement...I will update the README.
