### ISSUE TITLE
PROTOCOL

### ISSUE THREAD

**Issue by dozer1dave** [tmknight/docker-nordvpn#31]
Regardless of whether TECHNOLOGY is set to "OPENVPN" or "OpenVPN" I see the following in logs:
"Protocol setting is not available when the set technology is not OpenVPN."

It looks like it is setting the PROTOCOL to UDP regardless of PROTOCOL setting

**Comment by tmknight** [comment]
Please share the settings you've applied and the output of docker logs [container_name]

**Comment by tmknight** [comment]
I see it; addressed in [2.3.0-rc.2](https://github.com/tmknight/docker-nordvpn/releases/tag/2.3.0-rc.2)

**Comment by dozer1dave** [comment]
Fixed faster than I can respond.....THANKS @tmknight 

I'll test
