### ISSUE TITLE
Reconnection ignoring CONNECT country filter?

### ISSUE THREAD

**Issue by SteveyBoros** [tmknight/docker-nordvpn#91]
I'm not sure if this is a bug or not, perhaps I am just missing something config wise?

If the initial connection to a server fails when specifying a country, the reconnect attempt seems to ignore the country filter and uses the default recommended server that Nord suggests.

For example, in docker-compose.yml I set:

```
environment: 
    CONNECT: "NL" # Netherlands
```

The first connection attempt to NL fails, 60 seconds later it tries to reconnect but this time to a UK server (presumably the default Nord recommended one for my location)

```
vpn3  | ########################
vpn3  | 2024-03-03 18:59:57+0000        INFO    Target reconnect time is '2024-03-03 21:09:00+0000'
vpn3  | 2024-03-03 19:00:10+0000        INFO    Waiting for nord daemon to start...
vpn3  | 2024-03-03 19:00:12+0000        INFO    Firewall is up; traffic will be routed through vpn
vpn3  | 2024-03-03 19:00:12+0000        INFO    Enabling connection to secure interface and docker network
vpn3  | 2024-03-03 19:00:12+0000        INFO    Configuring and connecting NordVPN...
vpn3  | ########################
NordVPN Version 3.17.2
Technology is already set to 'NORDLYNX'.
Subnet 172.25.0.0/16 is already allowlisted.
Subnet 10.0.0.0/24 is already allowlisted.
vpn3  | Login successful; connection now in progress...
vpn3  | The recommended server is NL
Connecting to Netherlands #932 (nl932.nordvpn.com)
The VPN connection has failed. Please check your internet connection and try connecting to the VPN again. If the issue persists, contact our customer support.
Firewall is already set to 'enabled'.
Kill Switch is set to 'enabled' successfully.
vpn3  | ########################
vpn3  | 2024-03-03 19:00:44+0000        INFO    Enabling connection to IPv4 network 10.0.0.0/24
vpn3  | 2024-03-03 19:00:44+0000        INFO    Startup complete
vpn3  | 2024-03-03 19:00:44+0000        INFO    Target reconnect time is '2024-03-03 21:10:00+0000'
vpn3  | 2024-03-03 19:02:16+0000        WARNING Unstable connection detected
vpn3  | ########################
Status: Disconnected
Connecting to United Kingdom #2115 (uk2115.nordvpn.com)
The VPN connection has failed. Please check your internet connection and try connecting to the VPN again. If the issue persists, contact our customer support.
vpn3  | ########################
vpn3  | 2024-03-03 19:02:50+0000        INFO    Target reconnect time is '2024-03-03 21:12:00+0000'
vpn3  | 2024-03-03 19:04:23+0000        WARNING Unstable connection detected
vpn3  | ########################
Status: Disconnected
Connecting to United Kingdom #2275 (uk2275.nordvpn.com)
You are connected to United Kingdom #2275 (uk2275.nordvpn.com)!
vpn3  | ########################
vpn3  | 2024-03-03 19:04:27+0000        INFO    Target reconnect time is '2024-03-03 21:14:00+0000'
```

Am I perhaps doing something wrong here?

PS. The reason for the failing connection is simply because I hit the concurrent device limit, my internet dropped a few times and Nord hadn't timed me out yet. I have no issues with this obviously, just noting it for clarity.

**Comment by tmknight** [comment]
What occurs when you set FIREWALL=FALSE

**Comment by SteveyBoros** [comment]
Actually I just noticed that with the firewall off, the reconnect doesn't actually happen until RECONNECT_INTERVAL. Normally this would happen much sooner (CHECK_CONNECTION_INTERVAL?)

It's acting almost as though it thinks it's connected even though it failed?

`NordVPN Version 3.17.2
Technology is already set to 'NORDLYNX'.
Subnet 172.30.0.0/16 is already allowlisted.
Subnet 10.0.0.0/24 is already allowlisted.
vpn3  | Login successful; connection now in progress...
vpn3  | The recommended server is nl815
Connecting to Netherlands #815 (nl815.nordvpn.com)
The VPN connection has failed. Please check your internet connection and try connecting to the VPN again. If the issue persists, contact our customer support.
Firewall is already set to 'disabled'.
vpn3  | ########################
vpn3  | 2024-03-11 10:44:19+0000        INFO    Enabling connection to IPv4 network 10.88.0.0/24
vpn3  | 2024-03-11 10:44:19+0000        INFO    Startup complete
vpn3  | 2024-03-11 10:44:19+0000        INFO    Target reconnect time is '2024-03-11 12:54:00+0000'`

**Comment by SteveyBoros** [comment]
Sorry for the comment spam.

I had a quick look into code behind the connection/checking. Just to note I was using the CONNECT variable originally when I first posted this issue. I don't believe using CONNECT has the same restrictions with FIREWALL=TRUE that CONNECTION_FILTERS does?

I can only assume there are potentially two (unrelated?) issues here.

1. Reconnection on failure not obeying CONNECT
2. Failed connections when using FIREWALL=FALSE aren't detected

You will obviously be more informed than me though!

**Comment by SteveyBoros** [comment]
Last message on this one then, apologies for all the updates. I should stop posting prematurely!

So, even though the second patch fixes the problem of the initial connection failure, it does not fix $SERVER being NULL when reconnecting after failure (unstable connection). I suspect my patch only masks the real issue.

I'll do some more digging this evening.

**Comment by SteveyBoros** [comment]
[patch3.txt](https://github.com/tmknight/docker-nordvpn/files/14562715/patch3.txt)

I think this is the sanest way to fix this. Only setting SERVER when CONNECT is set. I think this keeps your logic intact for CONNECTION_FILTERS and Nord's firewall.

The pipefail is required otherwise the connection loop at the bottom of nord_connect just exits on a nordvpn connection failure (in my case). The problem with this is as stated earlier, the container then just assumes the VPN is online when it isn't. It's not a major issue now since setting SERVER (as above) fixes the reconnect attempt but there is a delay of CHECK_CONNECTION_INTERVAL before this happens which I think is undesirable.

I am sure you will know the best solution to this though. I hope this info at least saves you some time!

**Comment by tmknight** [comment]
Please submit as a PR and I'll take a look at it.

**Comment by SteveyBoros** [comment]
Cleaned it up and PR'd as requested https://github.com/tmknight/docker-nordvpn/pull/92. Not PR'd before, please forgive lack of proper etiquette.

**Comment by tmknight** [comment]
Good work; thanks for contributing to improving the project!
